{% set name = "lume-genesis" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b4789d057521890d8ebaefdac3ff46c10ae41041e56a6476fc9ebb62a0f3785f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scipy
    - genesis2
    - lume-base

test:
  imports:
    - genesis
  requires:
    - pytest
  source_files:
    - tests 
  commands:
    - pytest tests    

about:
  home: https://github.com/slaclab/{{ name }}
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Genesis tools for use in LUME
  description: |
    Genesis tools for use in LUME.

extra:
  recipe-maintainers:
    - balticfish
    - ChristopherMayes
